server:
  port: 1205
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://roundhouse.proxy.rlwy.net:54799/railway"
    username: "root"
    password: "KDOYiLpFYoRBzctmQaizlZdKLhgFcMJR"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update

upload:
  file:
    name: "profile-pictures/"

